apiVersion: apps/v1
kind: Deployment
metadata:
  name: sku
spec:
  selector:
    matchLabels:
      app: sku
  template:
    metadata:
      labels:
        app: sku
    spec:
      containers:
      - name: sku
        image: sku
        ports:
        - containerPort: 3000