name: Docker Image CI

on:
  pull_request:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ragdestyem/project_armazem
          token: ${{ secrets.PAT_TOKEN}}

      - name: Listar arquivos e pastas após o checkout
        run: |
          cd kong
          ls -la


