name: Docker Image CI

on:
  pull_request:
    branches:
      - main
jobs:
  check-application_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    - name: Build NestJS app
      run: npm run build  # ajuste o comando de build conforme sua configuração


