name: Docker Image CI

on:
  pull_request:
    branches:
      - main
jobs:
  generate_image_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/app:${{github.sha}}, ${{secrets.DOCKERHUB_USERNAME}}/app:lasted

  deploy-dev:
    needs:
      - generate_image_main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ragdestyem/project_armazem
          token: ${{ secrets.PAT_TOKEN}}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernets resources
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        
        run:
          (cd k8s/SKU && kustomize edit set image sku=$DOCKER_USERNAME/app:$GITHUB_SHA)
          
          
      - name: Commit
        run: |
          git config --local user.email "uppaplicativo@gmail.com"
          git config --local user.name "carlos"
          git commit -am "Bump docker version"
          git pull --rebase
          git push

